kind: Service
apiVersion: v1
metadata:
  name: {{ include "fibonacci.fullname" . }}
  labels:
    {{- include "fibonacci.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fibonacci.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
  type: {{ .Values.service.type }}