{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "fibonacci.fullname" . }}
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "fibonacci.fullname" . }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      minAllowed:
        cpu: {{ .Values.vpa.minAllowed.cpu }}
        memory: {{ .Values.vpa.minAllowed.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.maxAllowed.cpu }}
        memory: {{ .Values.vpa.maxAllowed.memory }}
      controlledResources: ["cpu", "memory"]
{{- end }}